### ISSUE TITLE
Getting version 0.4.0 on running "pip install radula"

### ISSUE THREAD

**Issue by icamys** [bibby/radula#11]
On installing this package getting version 0.4.0 instead of expected 0.8.1

**Comment by bibby** [comment]
This I cannot explain, nor can I reproduce.
I tried ubuntu 14.04 and 16.04 using docker.
Mind sharing information on your environment?

Thanks for these reports, btw.

**Comment by icamys** [comment]
@bibby 
I am using Python 2.7.12 on Ubuntu 16.04.3 LTS (no containers).

---

Looks like I found how to reproduce it and why it occurs. Previously I've tried to install radula using pip version 3.5:

```
$ pip --version
pip 9.0.1 from /home/icamys/.local/lib/python3.5/site-packages (python 3.5)
```

After that I've used pip2.7 to install radula and it worked well. Sorry, my bad. =)
