### ISSUE TITLE
Command to list bucket contents

### ISSUE THREAD

**Issue by adrianlzt** [bibby/radula#7]
Could be really useful a "ls" command.
Thanks!

**Comment by bibby** [comment]
`keys` is what you're looking for, with some glob support.
`radula keys bucket`
`radula keys bucket/path/` == `radula keys bucket/path/*`

Attempting to use `list` is currently my most common radula mistake. So yes! Definitely will be adding `ls` and `list` as an alias of `keys`.

**Comment by bibby** [comment]
New aliases `ls` and `list` have been added for `keys` on the `dev` branch. I'll try to explain in issue #8 about why  a merge is not happening immediately.
